// lib/mock-data.ts - Mock data untuk Phase 1 development

import type { Car, Customer, Order, ChatMessage } from "@/types";

// ============================================================================
// CARS DATA (15+ Mobil)
// ============================================================================

export const mockCars: Car[] = [
  {
    id: "car-001",
    name: "Avanza 1.3L",
    brand: "Toyota",
    model: "Avanza",
    year: 2023,
    category: "economy",
    pricePerDay: 200000,
    pricePerHour: 30000,
    transmission: "manual",
    seats: 7,
    fuelType: "bensin",
    mileage: 45000,
    images: [
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=500&q=80",
    ],
    description:
      "Mobil keluarga terjangkau dan reliable, cocok untuk perjalanan panjang. Kapasitas 7 penumpang, AC dingin, power steering.",
    availability: true,
    studentDiscount: 20,
    features: ["AC", "Power Steering", "ABS", "Kursi Empuk", "Trunk Besar"],
  },
  {
    id: "car-002",
    name: "HR-V 1.5L AT",
    brand: "Honda",
    model: "HR-V",
    year: 2022,
    category: "comfort",
    pricePerDay: 280000,
    pricePerHour: 42000,
    transmission: "automatic",
    seats: 5,
    fuelType: "bensin",
    mileage: 32000,
    images: ["https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=500&q=80"],
    description:
      "SUV modern dengan teknologi terkini. Automatic transmission, interior rapi, cocok untuk city driving maupun perjalanan jauh.",
    availability: true,
    studentDiscount: 15,
    features: [
      "AC",
      "Power Steering",
      "ABS",
      "Cruise Control",
      "Bluetooth",
      "Airbag",
    ],
  },
  {
    id: "car-003",
    name: "Xpander 1.5L",
    brand: "Mitsubishi",
    model: "Xpander",
    year: 2023,
    category: "comfort",
    pricePerDay: 300000,
    pricePerHour: 45000,
    transmission: "manual",
    seats: 7,
    fuelType: "bensin",
    mileage: 28000,
    images: ["/images/cars/xpander-1.jpg", "/images/cars/xpander-2.jpg"],
    description:
      "MPV modern dengan desain futuristik. Kapasitas 7 penumpang, interior luas, irit bahan bakar, cocok untuk keluarga.",
    availability: true,
    studentDiscount: 18,
    features: [
      "AC",
      "Power Steering",
      "ABS",
      "Airbag",
      "Roof Rack",
      "Panoramic Sunroof",
    ],
  },
  {
    id: "car-004",
    name: "Ayla 1.0L MT",
    brand: "Daihatsu",
    model: "Ayla",
    year: 2022,
    category: "economy",
    pricePerDay: 150000,
    pricePerHour: 22000,
    transmission: "manual",
    seats: 5,
    fuelType: "bensin",
    mileage: 52000,
    images: ["/images/cars/ayla-1.jpg", "/images/cars/ayla-2.jpg"],
    description:
      "Mobil city car terjangkau dan efisien bahan bakar. Pas untuk solo travel atau couple, mudah parkir di jalan sempit.",
    availability: true,
    studentDiscount: 25,
    features: ["AC", "Power Steering", "ABS", "MP3 Player"],
  },
  {
    id: "car-005",
    name: "Jazz 1.5L AT",
    brand: "Honda",
    model: "Jazz",
    year: 2023,
    category: "comfort",
    pricePerDay: 320000,
    pricePerHour: 48000,
    transmission: "automatic",
    seats: 5,
    fuelType: "bensin",
    mileage: 15000,
    images: ["/images/cars/jazz-1.jpg", "/images/cars/jazz-2.jpg"],
    description:
      "Hatchback premium dengan teknologi hybrid. Irit bensin, handling mantap, interior sporty. Cocok untuk anak muda.",
    availability: true,
    studentDiscount: 15,
    features: [
      "AC",
      "Power Steering",
      "ABS",
      "Hybrid Engine",
      "Cruise Control",
      "Touchscreen",
      "Reverse Camera",
    ],
  },
  {
    id: "car-006",
    name: "Innova 2.4L Diesel",
    brand: "Toyota",
    model: "Innova",
    year: 2022,
    category: "premium",
    pricePerDay: 450000,
    pricePerHour: 65000,
    transmission: "manual",
    seats: 7,
    fuelType: "diesel",
    mileage: 38000,
    images: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=500&q=80",
    ],
    description:
      "MPV mewah untuk keluarga besar. Diesel engine, tenaga besar, cocok untuk mudik atau perjalanan jauh dengan penumpang banyak.",
    availability: true,
    studentDiscount: 10,
    features: [
      "AC Dual Zone",
      "Power Steering",
      "ABS",
      "Airbag",
      "Leather Seats",
      "DVD Player",
      "4WD",
    ],
  },
  {
    id: "car-007",
    name: "Calya 1.2L MT",
    brand: "Daihatsu",
    model: "Calya",
    year: 2023,
    category: "economy",
    pricePerDay: 180000,
    pricePerHour: 27000,
    transmission: "manual",
    seats: 7,
    fuelType: "bensin",
    mileage: 22000,
    images: ["/images/cars/calya-1.jpg", "/images/cars/calya-2.jpg"],
    description:
      "MPV budget-friendly dengan kapasitas 7 orang. Hemat BBM, handle baik, cocok untuk rombongan mahasiswa.",
    availability: false,
    studentDiscount: 22,
    features: ["AC", "Power Steering", "ABS", "Manual Transmission"],
  },
  {
    id: "car-008",
    name: "Brio 1.2L MT",
    brand: "Honda",
    model: "Brio",
    year: 2022,
    category: "economy",
    pricePerDay: 160000,
    pricePerHour: 24000,
    transmission: "manual",
    seats: 5,
    fuelType: "bensin",
    mileage: 48000,
    images: ["/images/cars/brio-1.jpg", "/images/cars/brio-2.jpg"],
    description:
      "City car compact dan agile. Irit bahan bakar, mudah dikendarai, sempurna untuk jelajahi kota atau perjalanan singkat.",
    availability: true,
    studentDiscount: 20,
    features: ["AC", "Power Steering", "Tilt Steering", "Central Lock"],
  },
  {
    id: "car-009",
    name: "Rush 1.5L MT",
    brand: "Toyota",
    model: "Rush",
    year: 2023,
    category: "comfort",
    pricePerDay: 290000,
    pricePerHour: 44000,
    transmission: "manual",
    seats: 7,
    fuelType: "bensin",
    mileage: 18000,
    images: ["/images/cars/rush-1.jpg", "/images/cars/rush-2.jpg"],
    description:
      "SUV 7 seater dengan desain modern. Cocok untuk keluarga atau rombongan, ground clearance tinggi, off-road capable.",
    availability: true,
    studentDiscount: 17,
    features: [
      "AC",
      "Power Steering",
      "ABS",
      "Roof Rack",
      "Hill Start Assist",
    ],
  },
  {
    id: "car-010",
    name: "Ertiga 1.4L MT",
    brand: "Toyota",
    model: "Ertiga",
    year: 2022,
    category: "economy",
    pricePerDay: 210000,
    pricePerHour: 31000,
    transmission: "manual",
    seats: 7,
    fuelType: "bensin",
    mileage: 35000,
    images: ["/images/cars/ertiga-1.jpg", "/images/cars/ertiga-2.jpg"],
    description:
      "MPV ringan dan efisien. Cocok untuk keluarga kecil atau rombongan, interior rapi, spare parts mudah dicari.",
    availability: true,
    studentDiscount: 19,
    features: ["AC", "Power Steering", "ABS", "Airbag", "Central Lock"],
  },
  {
    id: "car-011",
    name: "CR-V 1.5L Turbo AT",
    brand: "Honda",
    model: "CR-V",
    year: 2023,
    category: "premium",
    pricePerDay: 500000,
    pricePerHour: 75000,
    transmission: "automatic",
    seats: 5,
    fuelType: "bensin",
    mileage: 8000,
    images: ["/images/cars/crv-1.jpg", "/images/cars/crv-2.jpg"],
    description:
      "SUV premium dengan teknologi canggih. Turbo engine, automatic transmission, interior mewah, cocok untuk business trip.",
    availability: true,
    studentDiscount: 12,
    features: [
      "AC Dual Zone",
      "Power Steering",
      "ABS",
      "Cruise Control",
      "Sunroof",
      "Leather Seats",
      "Touchscreen",
      "360 Camera",
    ],
  },
  {
    id: "car-012",
    name: "Fortuner 2.8L Diesel AT",
    brand: "Toyota",
    model: "Fortuner",
    year: 2022,
    category: "premium",
    pricePerDay: 550000,
    pricePerHour: 80000,
    transmission: "automatic",
    seats: 7,
    fuelType: "diesel",
    mileage: 25000,
    images: ["/images/cars/fortuner-1.jpg", "/images/cars/fortuner-2.jpg"],
    description:
      "SUV flagship dengan performa tinggi. Diesel turbo, 4WD, interior premium, cocok untuk executive atau keluarga mewah.",
    availability: true,
    studentDiscount: 8,
    features: [
      "AC Dual Zone",
      "Power Steering",
      "ABS",
      "Cruise Control",
      "Leather Seats",
      "Sunroof",
      "DVD Player",
      "4WD",
      "Hill Descent Control",
    ],
  },
  {
    id: "car-013",
    name: "Vios 1.5L MT",
    brand: "Toyota",
    model: "Vios",
    year: 2023,
    category: "comfort",
    pricePerDay: 240000,
    pricePerHour: 36000,
    transmission: "manual",
    seats: 5,
    fuelType: "bensin",
    mileage: 12000,
    images: ["/images/cars/vios-1.jpg", "/images/cars/vios-2.jpg"],
    description:
      "Sedan compact reliability champion. Irit bahan bakar, spare parts murah, nyaman untuk daily driver atau business.",
    availability: true,
    studentDiscount: 16,
    features: [
      "AC",
      "Power Steering",
      "ABS",
      "Airbag",
      "Power Window",
      "Central Lock",
    ],
  },
  {
    id: "car-014",
    name: "Veloz 1.5L MT",
    brand: "Toyota",
    model: "Veloz",
    year: 2023,
    category: "comfort",
    pricePerDay: 310000,
    pricePerHour: 46000,
    transmission: "manual",
    seats: 7,
    fuelType: "bensin",
    mileage: 5000,
    images: ["/images/cars/veloz-1.jpg", "/images/cars/veloz-2.jpg"],
    description:
      "MPV terbaru Toyota dengan design modern. Cocok untuk keluarga muda, interior spacious, fitur lengkap, harga kompetitif.",
    availability: true,
    studentDiscount: 14,
    features: [
      "AC",
      "Power Steering",
      "ABS",
      "Airbag",
      "Touchscreen",
      "Reverse Camera",
      "Power Window",
    ],
  },
  {
    id: "car-015",
    name: "Terios 1.5L MT",
    brand: "Daihatsu",
    model: "Terios",
    year: 2022,
    category: "comfort",
    pricePerDay: 270000,
    pricePerHour: 40000,
    transmission: "manual",
    seats: 5,
    fuelType: "bensin",
    mileage: 42000,
    images: ["/images/cars/terios-1.jpg", "/images/cars/terios-2.jpg"],
    description:
      "SUV 5 seater dengan handling bagus. All-wheel drive capable, cocok untuk adventure atau keluarga urban dengan budget moderate.",
    availability: true,
    studentDiscount: 18,
    features: [
      "AC",
      "Power Steering",
      "ABS",
      "Airbag",
      "Roof Rack",
      "All-wheel Drive",
    ],
  },
];

// ============================================================================
// CUSTOMERS DATA (5+ Pelanggan)
// ============================================================================

export const mockCustomers: Customer[] = [
  {
    id: "cust-001",
    email: "budi.santoso@student.ugm.ac.id",
    name: "Budi Santoso",
    phone: "+62812-1234-5678",
    birthDate: "2003-05-15",
    studentId: "UGM-2021-12345",
    address: "Jl. Kaliurang No. 45, Yogyakarta 55281",
    identityType: "ktp",
    identityNumber: "3402011503030001",
    isVerified: true,
    studentVerified: true,
    createdAt: "2025-01-10T08:30:00Z",
    updatedAt: "2025-06-20T14:15:00Z",
  },
  {
    id: "cust-002",
    email: "siti.nurhaliza@student.uii.ac.id",
    name: "Siti Nurhaliza",
    phone: "+62813-8765-4321",
    birthDate: "2004-03-22",
    studentId: "UII-2022-54321",
    address: "Jl. Condongcatur, Yogyakarta 55283",
    identityType: "sim",
    identityNumber: "3402-04-22-040394",
    isVerified: true,
    studentVerified: true,
    createdAt: "2025-02-14T10:45:00Z",
    updatedAt: "2025-06-18T09:20:00Z",
  },
  {
    id: "cust-003",
    email: "raka.wijaya@gmail.com",
    name: "Raka Wijaya",
    phone: "+62811-9876-5432",
    birthDate: "2002-07-08",
    studentId: "UNNES-2020-98765",
    address: "Jl. Adisumarmo, Yogyakarta 55281",
    identityType: "ktm",
    identityNumber: "C-1234-5678-90",
    isVerified: false,
    studentVerified: false,
    createdAt: "2025-03-20T15:30:00Z",
    updatedAt: "2025-03-20T15:30:00Z",
  },
  {
    id: "cust-004",
    email: "maya.putri@student.unjani.ac.id",
    name: "Maya Putri Antara",
    phone: "+62814-5555-6666",
    birthDate: "2004-11-30",
    studentId: "UNJANI-2022-11111",
    address: "Jl. Papanggungan, Yogyakarta 55281",
    identityType: "ktp",
    identityNumber: "3402013011040002",
    isVerified: true,
    studentVerified: true,
    createdAt: "2025-04-05T12:00:00Z",
    updatedAt: "2025-06-15T16:45:00Z",
  },
  {
    id: "cust-005",
    email: "anto.suryanto@business.com",
    name: "Anto Suryanto",
    phone: "+62821-2222-3333",
    birthDate: "1998-09-12",
    address: "Jl. Diponegoro No. 100, Yogyakarta 55143",
    identityType: "ktp",
    identityNumber: "3402019809980001",
    isVerified: true,
    studentVerified: false,
    createdAt: "2025-05-01T09:15:00Z",
    updatedAt: "2025-06-10T11:30:00Z",
  },
  {
    id: "cust-006",
    email: "lisa.chen@student.uad.ac.id",
    name: "Lisa Chen",
    phone: "+62819-7777-8888",
    birthDate: "2005-01-25",
    studentId: "UAD-2023-22222",
    address: "Jl. Ringroad Utara, Yogyakarta 55281",
    identityType: "sim",
    identityNumber: "3402-02-25-050562",
    isVerified: true,
    studentVerified: true,
    createdAt: "2025-05-15T14:20:00Z",
    updatedAt: "2025-06-19T10:50:00Z",
  },
];

// ============================================================================
// ORDERS DATA (10+ Transaksi)
// ============================================================================

export const mockOrders: Order[] = [
  {
    id: "order-001",
    customerId: "cust-001",
    carId: "car-001",
    rentalStartDate: "2025-06-20T10:00:00Z",
    rentalEndDate: "2025-06-22T10:00:00Z",
    pricePerDay: 200000,
    insuranceSelected: true,
    insurancePrice: 50000,
    subtotal: 450000,
    penaltyAccumulated: 0,
    status: "active",
    paymentMethod: "transfer",
    paymentStatus: "paid",
    documentsVerified: true,
    documentUrls: {
      ktpUrl: "/uploads/ktp-cust-001.jpg",
      simUrl: "/uploads/sim-cust-001.jpg",
    },
    notes: "Customer tambah asuransi comprehensive",
    createdAt: "2025-06-19T14:30:00Z",
    updatedAt: "2025-06-20T09:45:00Z",
  },
  {
    id: "order-002",
    customerId: "cust-002",
    carId: "car-002",
    rentalStartDate: "2025-06-21T08:00:00Z",
    rentalEndDate: "2025-06-23T18:00:00Z",
    rentalEndActualDate: "2025-06-24T02:30:00Z",
    pricePerDay: 280000,
    insuranceSelected: false,
    insurancePrice: 0,
    subtotal: 560000,
    penaltyAccumulated: 425000,
    status: "overdue",
    paymentMethod: "cash",
    paymentStatus: "partial",
    documentsVerified: true,
    documentUrls: {
      ktpUrl: "/uploads/ktp-cust-002.jpg",
      simUrl: "/uploads/sim-cust-002.jpg",
    },
    notes: "Keterlambatan 8.5 jam karena macet di jalan tol",
    createdAt: "2025-06-20T16:00:00Z",
    updatedAt: "2025-06-24T02:31:00Z",
  },
  {
    id: "order-003",
    customerId: "cust-001",
    carId: "car-005",
    rentalStartDate: "2025-06-25T14:00:00Z",
    rentalEndDate: "2025-06-27T14:00:00Z",
    pricePerDay: 320000,
    insuranceSelected: true,
    insurancePrice: 60000,
    subtotal: 700000,
    penaltyAccumulated: 0,
    status: "pending",
    paymentMethod: "transfer",
    paymentStatus: "unpaid",
    documentsVerified: false,
    documentUrls: {
      ktpUrl: "",
      simUrl: "",
    },
    notes: "Menunggu verifikasi dokumen",
    createdAt: "2025-06-22T11:20:00Z",
    updatedAt: "2025-06-22T11:20:00Z",
  },
  {
    id: "order-004",
    customerId: "cust-004",
    carId: "car-006",
    rentalStartDate: "2025-06-15T09:00:00Z",
    rentalEndDate: "2025-06-18T09:00:00Z",
    pricePerDay: 450000,
    insuranceSelected: true,
    insurancePrice: 100000,
    subtotal: 1450000,
    penaltyAccumulated: 0,
    status: "completed",
    paymentMethod: "transfer",
    paymentStatus: "paid",
    documentsVerified: true,
    documentUrls: {
      ktpUrl: "/uploads/ktp-cust-004.jpg",
      simUrl: "/uploads/sim-cust-004.jpg",
    },
    notes: "Mudik Lebaran, pelanggan puas",
    createdAt: "2025-06-10T09:00:00Z",
    updatedAt: "2025-06-18T10:15:00Z",
  },
  {
    id: "order-005",
    customerId: "cust-003",
    carId: "car-004",
    rentalStartDate: "2025-06-23T13:00:00Z",
    rentalEndDate: "2025-06-25T13:00:00Z",
    pricePerDay: 150000,
    insuranceSelected: false,
    insurancePrice: 0,
    subtotal: 300000,
    penaltyAccumulated: 0,
    status: "confirmed",
    paymentMethod: "cash",
    paymentStatus: "paid",
    documentsVerified: true,
    documentUrls: {
      ktpUrl: "/uploads/ktp-cust-003.jpg",
      simUrl: "/uploads/sim-cust-003.jpg",
      ktmUrl: "/uploads/ktm-cust-003.jpg",
    },
    notes: "Pembayaran tunai saat pickup",
    createdAt: "2025-06-18T15:45:00Z",
    updatedAt: "2025-06-23T13:00:00Z",
  },
  {
    id: "order-006",
    customerId: "cust-005",
    carId: "car-011",
    rentalStartDate: "2025-06-28T08:00:00Z",
    rentalEndDate: "2025-07-02T08:00:00Z",
    pricePerDay: 500000,
    insuranceSelected: true,
    insurancePrice: 150000,
    subtotal: 2650000,
    penaltyAccumulated: 0,
    status: "pending",
    paymentMethod: "card",
    paymentStatus: "unpaid",
    documentsVerified: false,
    documentUrls: {
      ktpUrl: "",
      simUrl: "",
    },
    notes: "Business trip ke Semarang",
    createdAt: "2025-06-20T10:30:00Z",
    updatedAt: "2025-06-20T10:30:00Z",
  },
  {
    id: "order-007",
    customerId: "cust-006",
    carId: "car-013",
    rentalStartDate: "2025-06-24T10:00:00Z",
    rentalEndDate: "2025-06-26T10:00:00Z",
    pricePerDay: 240000,
    insuranceSelected: false,
    insurancePrice: 0,
    subtotal: 480000,
    penaltyAccumulated: 0,
    status: "active",
    paymentMethod: "transfer",
    paymentStatus: "paid",
    documentsVerified: true,
    documentUrls: {
      ktpUrl: "/uploads/ktp-cust-006.jpg",
      simUrl: "/uploads/sim-cust-006.jpg",
    },
    notes: "Student discount 16% applied",
    createdAt: "2025-06-21T13:15:00Z",
    updatedAt: "2025-06-24T09:45:00Z",
  },
  {
    id: "order-008",
    customerId: "cust-002",
    carId: "car-009",
    rentalStartDate: "2025-07-01T16:00:00Z",
    rentalEndDate: "2025-07-05T16:00:00Z",
    pricePerDay: 290000,
    insuranceSelected: true,
    insurancePrice: 80000,
    subtotal: 1240000,
    penaltyAccumulated: 0,
    status: "pending",
    paymentMethod: "transfer",
    paymentStatus: "paid",
    documentsVerified: true,
    documentUrls: {
      ktpUrl: "/uploads/ktp-cust-002.jpg",
      simUrl: "/uploads/sim-cust-002.jpg",
    },
    notes: "Weekend getaway ke Dieng",
    createdAt: "2025-06-25T14:30:00Z",
    updatedAt: "2025-06-25T14:30:00Z",
  },
  {
    id: "order-009",
    customerId: "cust-004",
    carId: "car-003",
    rentalStartDate: "2025-06-18T12:00:00Z",
    rentalEndDate: "2025-06-19T12:00:00Z",
    pricePerDay: 300000,
    insuranceSelected: false,
    insurancePrice: 0,
    subtotal: 300000,
    penaltyAccumulated: 150000,
    status: "overdue",
    paymentMethod: "cash",
    paymentStatus: "partial",
    documentsVerified: true,
    documentUrls: {
      ktpUrl: "/uploads/ktp-cust-004.jpg",
      simUrl: "/uploads/sim-cust-004.jpg",
    },
    notes: "Keterlambatan 3 jam, denda Rp150k",
    createdAt: "2025-06-15T10:00:00Z",
    updatedAt: "2025-06-19T15:00:00Z",
  },
  {
    id: "order-010",
    customerId: "cust-001",
    carId: "car-008",
    rentalStartDate: "2025-07-05T09:00:00Z",
    rentalEndDate: "2025-07-07T09:00:00Z",
    pricePerDay: 160000,
    insuranceSelected: true,
    insurancePrice: 30000,
    subtotal: 350000,
    penaltyAccumulated: 0,
    status: "pending",
    paymentMethod: "transfer",
    paymentStatus: "paid",
    documentsVerified: true,
    documentUrls: {
      ktpUrl: "/uploads/ktp-cust-001.jpg",
      simUrl: "/uploads/sim-cust-001.jpg",
    },
    notes: "City exploration, student discount 20%",
    createdAt: "2025-06-28T16:45:00Z",
    updatedAt: "2025-06-28T16:45:00Z",
  },
  {
    id: "order-011",
    customerId: "cust-003",
    carId: "car-010",
    rentalStartDate: "2025-06-26T11:00:00Z",
    rentalEndDate: "2025-06-29T11:00:00Z",
    pricePerDay: 210000,
    insuranceSelected: false,
    insurancePrice: 0,
    subtotal: 630000,
    penaltyAccumulated: 0,
    status: "cancelled",
    paymentMethod: "transfer",
    paymentStatus: "unpaid",
    documentsVerified: false,
    documentUrls: {
      ktpUrl: "",
      simUrl: "",
    },
    notes: "Customer cancel due to medical emergency",
    createdAt: "2025-06-23T09:20:00Z",
    updatedAt: "2025-06-24T08:00:00Z",
  },
];

// ============================================================================
// CHAT MESSAGES DATA (15+ Messages)
// ============================================================================

export const mockMessages: ChatMessage[] = [
  {
    id: "msg-001",
    orderId: "order-001",
    customerId: "cust-001",
    senderType: "customer",
    message: "Halo, saya mau tanya tentang asuransi comprehensive",
    timestamp: "2025-06-20T10:15:00Z",
    isRead: true,
  },
  {
    id: "msg-002",
    orderId: "order-001",
    customerId: "cust-001",
    adminId: "admin-001",
    senderType: "admin",
    message:
      "Halo Budi! Asuransi comprehensive mencakup kerusakan minor, batu loncatan, dan pencurian. Premium Rp50.000/hari.",
    timestamp: "2025-06-20T10:16:30Z",
    isRead: true,
  },
  {
    id: "msg-003",
    orderId: "order-001",
    customerId: "cust-001",
    senderType: "customer",
    message: "Oke, saya ambil asuransi comprehensive ya",
    timestamp: "2025-06-20T10:17:15Z",
    isRead: true,
  },
  {
    id: "msg-004",
    orderId: "order-002",
    customerId: "cust-002",
    senderType: "customer",
    message: "Saya kira bisa diperpanjang sampai jam 3 sore",
    timestamp: "2025-06-24T01:45:00Z",
    isRead: true,
  },
  {
    id: "msg-005",
    orderId: "order-002",
    customerId: "cust-002",
    adminId: "admin-002",
    senderType: "admin",
    message:
      "Siti, Anda terlambat 8.5 jam. Denda Rp50.000/jam = Rp425.000 total. Silakan transfer atau bayar cash saat serah terima.",
    timestamp: "2025-06-24T02:31:00Z",
    isRead: true,
  },
  {
    id: "msg-006",
    orderId: "order-002",
    customerId: "cust-002",
    senderType: "customer",
    message: "Baik admin, saya akan bayar pas serah terima mobilnya",
    timestamp: "2025-06-24T02:35:00Z",
    isRead: true,
  },
  {
    id: "msg-007",
    orderId: "order-003",
    customerId: "cust-001",
    senderType: "customer",
    message: "Dokumen saya sudah diunggah, kapan bisa dikonfirmasi?",
    timestamp: "2025-06-22T12:00:00Z",
    isRead: true,
  },
  {
    id: "msg-008",
    orderId: "order-003",
    customerId: "cust-001",
    adminId: "admin-003",
    senderType: "admin",
    message: "Dokumen sedang diverifikasi oleh tim kami. Akan selesai dalam 1x24 jam.",
    timestamp: "2025-06-22T12:05:00Z",
    isRead: true,
  },
  {
    id: "msg-009",
    orderId: "order-004",
    customerId: "cust-004",
    senderType: "customer",
    message: "Mobilnya dalam kondisi sangat bagus, terimakasih!",
    timestamp: "2025-06-18T09:30:00Z",
    isRead: true,
  },
  {
    id: "msg-010",
    orderId: "order-004",
    customerId: "cust-004",
    adminId: "admin-001",
    senderType: "admin",
    message:
      "Terima kasih atas review positifnya Maya! Semoga perjalanannya lancar dan selamat sampai tujuan.",
    timestamp: "2025-06-18T09:35:00Z",
    isRead: true,
  },
  {
    id: "msg-011",
    orderId: "order-005",
    customerId: "cust-003",
    senderType: "customer",
    message:
      "Apakah bisa ambil mobil sekarang juga? Penerbangan saya terlalu cepat",
    timestamp: "2025-06-23T13:30:00Z",
    isRead: false,
  },
  {
    id: "msg-012",
    orderId: "order-005",
    customerId: "cust-003",
    adminId: "admin-002",
    senderType: "admin",
    message: "Maaf Raka, mobilnya masih dalam perjalanan pickup. Estimasi 30 menit lagi siap di lokasi Anda.",
    timestamp: "2025-06-23T13:35:00Z",
    isRead: false,
  },
  {
    id: "msg-013",
    orderId: "order-006",
    customerId: "cust-005",
    senderType: "customer",
    message:
      "Berapa harga untuk CR-V premium? Ada diskon corporate tidak?",
    timestamp: "2025-06-20T10:45:00Z",
    isRead: true,
  },
  {
    id: "msg-014",
    orderId: "order-006",
    customerId: "cust-005",
    adminId: "admin-001",
    senderType: "admin",
    message:
      "CR-V premium Rp500.000/hari dengan full insurance. Untuk corporate bulk order kami ada diskon khusus 10-15%. Silakan hubungi sales manager kami.",
    timestamp: "2025-06-20T11:00:00Z",
    isRead: true,
  },
  {
    id: "msg-015",
    orderId: "order-008",
    customerId: "cust-002",
    senderType: "customer",
    message: "Saya akan pickup Rush di jam 4 sore tepat waktu",
    timestamp: "2025-06-30T16:30:00Z",
    isRead: true,
  },
];
